import settingsSrc from "./settings.ts?raw"
import rendererSrc from "./three-renderer.ts?raw"
import type { StickerSettings } from "./settings"

/** Integration instructions shown (and copyable) after download. */
export function buildIntegrationInstructions(): string {
  return `Integrate the HoloSticker component (generated by holosticker.dev):

1. Save holo-sticker.tsx into your components directory
   (e.g. components/holo-sticker.tsx).
2. Save holo-sticker-art.png into public/ so it serves from
   /holo-sticker-art.png. To use a different location, pass
   artSrc="/your/path.png".
3. Install the only dependency:
   npm install three
4. Render it - the canvas fills its container, so size it via className:
   <HoloSticker className="size-64" />

Optional props:
- artSrc: string - path to the artwork image (default "/holo-sticker-art.png")
- settings: Partial<StickerSettings> - override any dial, e.g. {{ peelAmount: 0 }}
- interactive: boolean - pointer tilt on/off (default true)

Notes for agents: the file is fully self-contained (renderer + types inlined),
renders a transparent WebGL canvas, and needs no CSS. Do not split the file.`
}

/**
 * Build a self-contained shadcn-style component: the full renderer and
 * settings module inlined, artwork loaded from a public path, and the
 * current dials as the default settings. Only dependency: three.
 */
export function buildReactComponent(
  settings: StickerSettings,
  name: string,
): string {
  // strip relative imports (the modules are concatenated into one file)
  // and hoist the three import to the top of the generated file
  // drop the GIF/GLB export methods: they'd pull gifenc and the three
  // examples into the generated file, and the component doesn't need them
  const stripped = rendererSrc.replace(
    /\n {2}\/\* react-export:strip-start[\s\S]*?react-export:strip-end \*\//,
    "",
  )
  const renderer = stripped
    .split("\n")
    .filter(
      (l) =>
        !l.startsWith("import * as THREE") &&
        !l.startsWith('import { peelAngles } from "./settings"') &&
        !l.startsWith("import type") &&
        !l.startsWith("import {"),
    )
    .join("\n")

  return `/**
 * HoloSticker - generated by Holosticker (https://holosticker.dev)
 *
 * A holographic sticker of "${name}" as a single-file React component,
 * shadcn style: copy this file into your components directory.
 *
 * Install the only dependency:
 *   npm install three
 *
 * Setup:
 *   1. Put holo-sticker-art.png in public/ (or pass artSrc)
 *   2. npm install three
 *
 * Usage:
 *   <HoloSticker className="size-64" />
 *   <HoloSticker className="size-64" settings={{ peelAmount: 0 }} />
 */
import * as React from "react"
import * as THREE from "three"

/* ------------------------------------------------------------------ */
/* settings                                                            */
/* ------------------------------------------------------------------ */
${settingsSrc}

/* ------------------------------------------------------------------ */
/* renderer                                                            */
/* ------------------------------------------------------------------ */
${renderer}

/* ------------------------------------------------------------------ */
/* component                                                           */
/* ------------------------------------------------------------------ */

/** The dials as they were at export time. */
const STICKER_SETTINGS: StickerSettings = ${JSON.stringify(settings, null, 2)}

export interface HoloStickerProps {
  className?: string
  /** Path to the artwork image. Default "/holo-sticker-art.png". */
  artSrc?: string
  /** Override any generated setting. */
  settings?: Partial<StickerSettings>
  /** Tilt toward the pointer. Default true. */
  interactive?: boolean
}

export default function HoloSticker({
  className,
  artSrc = "/holo-sticker-art.png",
  settings,
  interactive = true,
}: HoloStickerProps) {
  const ref = React.useRef<HTMLCanvasElement>(null)
  const aspectRef = React.useRef(1)

  React.useEffect(() => {
    const canvas = ref.current
    if (!canvas) return
    const renderer = new HoloRenderer(canvas)
    const merged = { ...STICKER_SETTINGS, ...settings }
    let disposed = false
    let raf = 0
    void (async () => {
      const blob = await (await fetch(artSrc)).blob()
      const bitmap = await createImageBitmap(blob)
      if (disposed) return
      aspectRef.current = bitmap.width / bitmap.height
      renderer.setImage(bitmap)
    })()
    const draw = () => {
      raf = requestAnimationFrame(draw)
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      const w = Math.round(canvas.clientWidth * dpr)
      const h = Math.round(canvas.clientHeight * dpr)
      if (w > 0 && h > 0 && (canvas.width !== w || canvas.height !== h)) {
        canvas.width = w
        canvas.height = h
      }
      if (canvas.width === 0) return
      renderer.render({ settings: merged, imgAspect: aspectRef.current })
    }
    draw()
    const onMove = (e: PointerEvent) => {
      if (!interactive) return
      const rect = canvas.getBoundingClientRect()
      renderer.setTilt(
        ((e.clientX - rect.left) / rect.width) * 2 - 1,
        1 - ((e.clientY - rect.top) / rect.height) * 2,
      )
    }
    const onLeave = () => renderer.setTilt(0, 0)
    canvas.addEventListener("pointermove", onMove)
    canvas.addEventListener("pointerleave", onLeave)
    return () => {
      disposed = true
      cancelAnimationFrame(raf)
      canvas.removeEventListener("pointermove", onMove)
      canvas.removeEventListener("pointerleave", onLeave)
    }
  }, [artSrc, settings, interactive])

  return <canvas ref={ref} className={className} />
}
`
}
